### ISSUE TITLE
使用go get命令时提示无法找到cqcfg

### ISSUE THREAD

**Issue by EnderByEndera** [Tnze/CoolQ-Golang-SDK#11]
go get github.com/Tnze/CoolQ-Golang-SDK/v2/tools/cqcfg
package github.com/Tnze/CoolQ-Golang-SDK/v2/tools/cqcfg: cannot find package "github.com/Tnze/CoolQ-Golang-SDK/v2/tools/cqcfg" in any of:
	/usr/lib/golang/src/github.com/Tnze/CoolQ-Golang-SDK/v2/tools/cqcfg (from $GOROOT)
	/opt/gopath/src/github.com/Tnze/CoolQ-Golang-SDK/v2/tools/cqcfg (from $GOPATH)
我按照readme里面的步骤，却提示无法找到包，

**Comment by Tnze** [comment]
要在你项目根目录下go get

**Comment by Xumany** [comment]
你说的在根目录 是在 GOPATH 目录里面吗？@Tnze

**Comment by Tnze** [comment]
不是，是有`go.mod`文件的目录
