### ISSUE TITLE
sqlite3 支持

### ISSUE THREAD

**Issue by doylecnn** [Tnze/CoolQ-Golang-SDK#12]
尝试在项目中引入 github.com/mattn/go-sqlite3

但编译的 dll 总是无法被酷q 正确 load。

折腾后发现，只要引入 go-sqlite3 编译出来的 dll 就一定无法被酷q 正确加载，总是报
>错误：不是合法的应用(LoadLibrary 失败，GetLastError=126)(-103)

附上最小测试:

```
package main

import (
	"github.com/Tnze/CoolQ-Golang-SDK/cqp"

	_ "github.com/mattn/go-sqlite3"
)

//go:generate cqcfg -c .
// cqp: 名称: 测试
// cqp: 版本: 1.0.0:0
// cqp: 作者: doylecnn
// cqp: 简介: 测试
func main() { /*此处应当留空*/ }

func init() {
	cqp.AppID = "me.robirt.test" // TODO: 修改为这个插件的ID
	cqp.PrivateMsg = onPrivateMsg
}

func onPrivateMsg(subType, msgID int32, fromQQ int64, msg string, font int32) int32 {
	cqp.SendPrivateMsg(fromQQ, msg) //复读机
	return 0
}
```

**Comment by Tnze** [comment]
https://github.com/miaoscraft/SiS
我这个项目用过Sqlite3的库，可以正常编译，可以用

**Comment by Tnze** [comment]
![批注 2020-03-03 151155.png](https://i.loli.net/2020/03/03/SrbFIxv2XeAg79p.png)
你的例子我可以编译出来，可以正常加载。
可能你用的gcc有问题

**Comment by doylecnn** [comment]
使用的 gcc 环境来自 msys2 下的 mingw32。编译其它项目也都没有问题。
请问您使用的 gcc 环境是什么样的

**Comment by doylecnn** [comment]
使用TDM-GCC 后正常了……
