### ISSUE TITLE
dll编译成功，但开发者模式下启用应用时酷Q发生错误

### ISSUE THREAD

**Issue by yliu7949** [Tnze/CoolQ-Golang-SDK#17]
- gcc版本gcc version 9.2.0 (tdm64-1)
- 在Win10上开发，使用批处理Build.bat得到app.json和app.dll，显示'Build success!'，无报错（除了统计Git提交数失败的警告外）
- Win10酷Q，开发者模式下将得到的dll和json放入指定的文件夹/dev/me.cqp.tom.chattest，'应用管理'菜单内点击启用该插件后，酷Q立即报错。报错信息截图如下：
![报错信息](https://user-images.githubusercontent.com/54410385/81059583-40058980-8f03-11ea-9e25-d9e97a5bad63.png)
![报错信息2](https://user-images.githubusercontent.com/54410385/81059598-47c52e00-8f03-11ea-8942-95dc080a3310.png)
- 给出最简短代码如下：
app.go文件
```golang
package main

import (
	"fmt"
	"github.com/Tnze/CoolQ-Golang-SDK/cqp"
	"github.com/yliu7949/MCDaemon-go/plugins/ChatPlugin"
)

//go:generate cqcfg -c .
// cqp: 名称: CoolQ-ChatTest
// cqp: 版本: 1.0.0:1
// cqp: 作者: Tom
// cqp: 简介: 在QQ群里使用Websocket进行通讯~
func main() { /*此处应当留空*/ }

func init() {
	cqp.AppID = "me.cqp.tom.chattest" // TODO: 修改为这个插件的ID
	cqp.PrivateMsg = onPrivateMsg
}

func onPrivateMsg(subType, msgID int32, fromQQ int64, msg string, font int32) int32 {
	if msg[:5] == "#chat" {
		handleCmd(msg,fromQQ)
	}
	return 0
}

func handleCmd(msg string, fromQQ int64) {
	packageChan = make(chan *msgPackage, ChanMaxSize)
	fmt.Println(packageChan)
	go func() {fmt.Println("123")}()
	cqp.SendPrivateMsg(fromQQ, msg)
	return
}

var packageChan chan *msgPackage

const ChanMaxSize int = 20

type msgPackage struct {
	From int //服务器id
	Msg  *ChatPlugin.Message
}
```
go.mod文件
```golang
module main

go 1.13

require (
	github.com/Tnze/CoolQ-Golang-SDK v1.2.1
	github.com/yliu7949/MCDaemon-go v0.0.0-20200505071320-e4adce8ba83e
)
```
- 值得提到的是：当我继续删掉app.go中的代码，使得app.go几乎没什么功能时，编译成功，酷Q加载运行成功；以前使用golang SDK开发的一切正常的酷Q项目，现在重新编译、加载依旧没有任何问题。因此，问题可能出现在我的代码中。
- 我的开发目的是使用websocket与聊天服务器进行通讯。现在对于这个问题没有头绪，可能是channel的问题？还是import的包的问题？（不应该吧。）
- 期待实现的结果：找出报错原因，修正代码后能正常加载该app。谢谢！

**Comment by Tnze** [comment]
麻烦看一下酷Q日志中是否有有帮助的信息？

**Comment by yliu7949** [comment]
![日志-警告](https://user-images.githubusercontent.com/54410385/81062065-ee133280-8f07-11ea-8a28-68631f822f55.png)

**Comment by Tnze** [comment]
你可以尝试编译以下代码
```go
package main

import _ "github.com/yliu7949/MCDaemon-go/plugins/ChatPlugin"

func main() {

}
```
它会输出
```
读取配置文件失败: open MCD_conf.ini: The system cannot find the file specified.
```
能理解嘛，这个库擅自在init函数内读取配置文件，而且当失败时直接通过os.Exit等方法关闭进程，导致酷Q启动该插件的整个进程被关闭。所以包括SDK、酷Q本身都无法捕获这个错误并输出到日志

**Comment by Tnze** [comment]
你可以理解为这个库有很严重的副作用，光是导入它就会导致程序异常

**Comment by yliu7949** [comment]
好的，我明白了，谢谢您的热情帮助🙏
