### ISSUE TITLE
自定义菜单按钮

### ISSUE THREAD

**Issue by Zhwt** [Tnze/CoolQ-Golang-SDK#18]
如题, 看了一圈文档和 issue 里的截图, 发现好像没有菜单功能, 所有的菜单都是一个 "详情", 实际上只需要加入对于菜单项点击的处理事件就行了, 至于去拉出来 GUI 界面之类的事情就从自己的函数里处理了

函数头都拟好了, 就叫:

```go
// 或者 SetMenuItem
func AddMenuItem(title string, position uint8, handler func() int32) int32
```

**Comment by Tnze** [comment]
有大佬研究过了，当前版本是可以做到的，应该只要这样写就可以了

```go
// cqp: ....
// .....
// cqp: 菜单: 设置 OpenSettingForm
func main() {}

//export OpenSettingForm
func OpenSettingForm() {
    // code
}
```

**Comment by Zhwt** [comment]
试了一下, 是会自动生成对应的 json 了, 但是对应的函数调不了, 可能是我 cgo 设置的问题, 导出的 DLL 里面就没这个函数 ( 捂脸

**Comment by Tnze** [comment]
对了，你在开头加一句`import "C"`

**Comment by Zhwt** [comment]
谢谢, 确实加上这句之后就可以用了
