### ISSUE TITLE
手动发送一个文件或远程链接请求给对方时,若对方接收.coolQ直接异常终止.而发送文字正常.

### ISSUE THREAD

**Issue by abcdefg4564** [Tnze/CoolQ-Golang-SDK#19]
手动发送一个文件或远程链接请求给对方时,若对方接收.coolQ直接异常终止.而发送文字正常.
报错信息:
很抱歉,应用模块发生错误. (9N2TBJ)
XXXX
图片为下方链接,不知道能不能正常显示:
![`8J`)$}PY%5K)A{`Z8CA{07](https://user-images.githubusercontent.com/36299628/85828566-499cc680-b7bb-11ea-81bd-0fc0e3aa1e49.png)

**Comment by Tnze** [comment]
看看代码

**Comment by abcdefg4564** [comment]
附件app.go



传文件或远程时,收到的msg转发消息都是空,#号不是消息部分.
其它聊天收到的Ok.








------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Tnze"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月26日(星期五) 下午5:55
收件人:&nbsp;"Tnze/CoolQ-Golang-SDK"<CoolQ-Golang-SDK@noreply.github.com&gt;;
抄送:&nbsp;"传奇阿康"<19502651@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Tnze/CoolQ-Golang-SDK] 手动发送一个文件或远程链接请求给对方时,若对方接收.coolQ直接异常终止.而发送文字正常. (#19)





 
看看代码

**Comment by Tnze** [comment]
看不到附件

**Comment by Tnze** [comment]
真的看不到附件
