### ISSUE TITLE
大佬是个狼人啊

### ISSUE THREAD

**Issue by Yanwensiyi** [Tnze/CoolQ-Golang-SDK#3]
不说多的，就两个字，牛逼！

**Comment by Tnze** [comment]
🙏谢谢。
请问还有别的事吗？

**Comment by Yanwensiyi** [comment]
没事，希望大佬继续加油

**Comment by Tnze** [comment]
![23C37B49AA33E8E1C8CBDE1011588420](https://user-images.githubusercontent.com/19628575/69902485-71fd4780-13c9-11ea-8d6b-79c8fc1f1c21.jpg)

**Comment by Yanwensiyi** [comment]
！果然大佬都是夜猫子吗！

**Comment by Tnze** [comment]
都还没到12点呢！

**Comment by Yanwensiyi** [comment]
嗯嗯，大佬nb（来自大一新生的无奈，11点熄灯）

**Comment by Tnze** [comment]
我们也11点熄灯（我大二）

**Comment by Yanwensiyi** [comment]
大佬才大二的吗？！那我们应该是同龄耶，我是00年的

**Comment by Tnze** [comment]
是的

**Comment by Yanwensiyi** [comment]
………………那就不多说了，晚安吧大佬（话说为啥我就不能搞出点名堂呜呜呜）
