### ISSUE TITLE
你好，能抽空把好友列表相关接口加上吗？

### ISSUE THREAD

**Issue by vinuu** [Tnze/CoolQ-Golang-SDK#4]
你好，能抽空把好友列表相关接口加上吗？

**Comment by Tnze** [comment]
是这样，我最近没有Windows设备，而SDK无法在macOS上编译和测试。  
刚刚加了GetFriendList接口，但是不知道能不能用。

**Comment by Tnze** [comment]
你可以试一下看能不能用
```bash
go get -u github.com/Tnze/CoolQ-Golang-SDK/cqp
```
v1.1.0

**Comment by vinuu** [comment]
更新试了，好像不行。
![image](https://user-images.githubusercontent.com/1614496/69908837-fda7c000-142b-11ea-92c0-9f6bb1eaf76b.png)

**Comment by Tnze** [comment]
用defer把panic捕获了之后用cqp.AddLog输出，不然看不出来问题在哪

**Comment by vinuu** [comment]
看了其他SDK，参数的原因。
![image](https://user-images.githubusercontent.com/1614496/69910408-1ae98800-1446-11ea-95ef-3f5a1de3791f.png)
