### ISSUE TITLE
刚接触golang 不久 对于gcc 有点问题想请教下

### ISSUE THREAD

**Issue by xingye1997** [Tnze/CoolQ-Golang-SDK#7]
请问 我现在装的64位golang  ,没有安装gcc,
如果要编写酷Q 插件 ，要把golang 换成32位的吗？
gcc 是用64的还是32的，希望能出个入门教程。

**Comment by Tnze** [comment]
都可以

**Comment by Tnze** [comment]
关于编译的环境以及流程，我这不方便仔细讲。但是  
你可以去看看`build.bat`，或者GitHub Actions，或者Dockerfile，或者其他[CI](https://ci.appveyor.com/project/Tnze/sis/builds/29748898)。

以上都是关于如何编译出`app.dll`以及生成`app.json`这两个文件，剩下的事就是看看酷Q文库教你怎么把插件打包成cpk文件，就可以发布了。
