### ISSUE TITLE
这个函数用不了，每次返回值是-99

### ISSUE THREAD

**Issue by lolieatapple** [Tnze/CoolQ-Golang-SDK#9]
https://github.com/Tnze/CoolQ-Golang-SDK/blob/f7266c1bbc4b0e71af4582b994c79568aa8679db/cqp/apis.go#L64

这个函数用不了啊，不能撤回群消息。也不能撤回自己的消息。

**Comment by Tnze** [comment]
请你查看酷Q的日志，撤回消息需要酷Q Pro。
